DROP TABLE IF EXISTS `Airport`;
CREATE TABLE `Airport` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` INT UNSIGNED,
  `title` VARCHAR(128) NOT NULL,
  `iata` CHAR(3) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;