DROP TABLE IF EXISTS `Review`;
CREATE TABLE `Review` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED DEFAULT 0,
  `name` VARCHAR(32) NOT NULL,
  `review` TEXT,
  `rating` TINYINT DEFAULT 5,
  `created` DATETIME DEFAULT NOW(),
  `modified` DATETIME DEFAULT NOW(),
  `status` TINYINT DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;