DROP TABLE IF EXISTS `Content`;
CREATE TABLE `Content` (
  `id`            INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `parentId`      INT UNSIGNED DEFAULT 0,
  `routeId`       INT UNSIGNED,
  `imageId`       INT UNSIGNED DEFAULT NULL,
  `type`          ENUM('Article', 'Category', 'Component', 'Tag') NOT NULL,
  `subtype`       ENUM('', 'Blog', 'News', 'Video') DEFAULT '',
  `title`         VARCHAR(128) NOT NULL,
  `summary`       TEXT DEFAULT NULL,
  `content`       TEXT DEFAULT NULL,
  `seo`           JSON CHECK (JSON_VALID(`seo`)),
  `media`         JSON CHECK (JSON_VALID(`media`)),
  `params`        JSON CHECK (JSON_VALID(`params`)),
  `status`        ENUM('Publish', 'Unpublish', 'Archive', 'Trash') NOT NULL DEFAULT 'Publish',
  `activeOn`     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `archiveOn`     TIMESTAMP DEFAULT NULL,
  `createdOn`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `displayOrder`  INT DEFAULT 0,
  FOREIGN KEY (`routeId`) REFERENCES `Route`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`imageId`) REFERENCES `Media`(`id`) ON DELETE SET NULL,
  INDEX idxType (`type`),
  INDEX idxStatus (`status`),
  INDEX idxPublishAt (`activeOn`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;
