DROP TABLE IF EXISTS `IPAddress`;
CREATE TABLE `IPAddress` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ipaddress` VARCHAR(45) NOT NULL UNIQUE,
  `encoded` varbinary(16),
  `block` TINYINT(3) DEFAULT 0,
  `created` DATETIME DEFAULT NOW(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;

