DROP TABLE IF EXISTS `Phone`;
CREATE TABLE `Phone` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` INT UNSIGNED NOT NULL,
  `tel` VARCHAR(16) NOT NULL,
  `extension` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;