DROP TABLE IF EXISTS `Session`;
CREATE TABLE `Session` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` INT UNSIGNED NOT NULL DEFAULT 0,
  `token` VARCHAR(64) UNIQUE,
  `block` TINYINT(3) DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;
