DROP TABLE IF EXISTS `TimeZone`;
CREATE TABLE `timezone` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timezone` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;
