DROP TABLE IF EXISTS `TokenForm`;
CREATE TABLE `TokenForm` (
  `session` INT UNSIGNED NOT NULL UNIQUE,
  `token` VARCHAR(64) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  `expires` DATETIME NOT NULL DEFAULT DATE_ADD(NOW(), INTERVAL 1 DAY),
  PRIMARY KEY (`user`, `token`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;
