DROP TABLE IF EXISTS `Url`;
CREATE TABLE `Url` (
  `id`          INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `url`         TEXT NOT NULL UNIQUE,
  `scheme`      ENUM('http', 'https') NOT NULL DEFAULT 'https',
  `host`        VARCHAR(256) NOT NULL,
  `path`        TEXT,
  `parts`       JSON CHECK (JSON_VALID(`parts`)),
  `file`        VARCHAR(512) NOT NULL,
  `extension`   ENUM(
    'aac',
    'avi',
    'bmp',
    'css',
    'csv',
    'doc',
    'docx',
    'eml',
    'flac',
    'gif',
    'gltf',
    'gz',
    'htm',
    'html',
    'ico',
    'iges',
    'igs',
    'jpeg',
    'jpg',
    'js',
    'json',
    'jsonld',
    'md',
    'mesh',
    'mime',
    'mov',
    'mp3',
    'mp4',
    'mpeg',
    'mpg',
    'msh',
    'obj',
    'ogg',
    'ogv',
    'otf',
    'pdf',
    'png',
    'ppt',
    'pptx',
    'svg',
    'swf',
    'tif',
    'tiff',
    'ttf',
    'txt',
    'vrml',
    'wav',
    'weba',
    'webm',
    'webp',
    'woff',
    'woff2',
    'wrl',
    'xls',
    'xlsx',
    'xml',
    'zip'
  ) NOT NULL,
  `type`        ENUM(
    'Archive',
    'Audio',
    'CSS',
    'CSV',
    'Font',
    'HTML',
    'Image',
    'JSON',
    'JavaScript',
    'PDF',
    'Text',
    'Video',
    'XML') NOT NULL,

  `mime`        ENUM(
    'text/plain',
    'text/html',
    'text/css',
    'text/javascript',
    'text/xml',
    'text/csv',
    'text/markdown',
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/svg+xml',
    'image/bmp',
    'image/tiff',
    'image/vnd.microsoft.icon',
    'audio/mpeg',
    'audio/ogg',
    'audio/wav',
    'audio/webm',
    'audio/aac',
    'audio/flac',
    'video/mp4',
    'video/mpeg',
    'video/ogg',
    'video/webm',
    'video/avi',
    'video/quicktime',
    'application/javascript',
    'application/json',
    'application/xml',
    'application/pdf',
    'application/zip',
    'application/gzip',
    'application/x-www-form-urlencoded',
    'application/octet-stream',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/x-shockwave-flash',
    'application/ld+json',
    'application/vnd.api+json',
    'multipart/form-data',
    'multipart/byteranges',
    'multipart/alternative',
    'multipart/mixed',
    'font/ttf',
    'font/otf',
    'font/woff',
    'font/woff2',
    'model/iges',
    'model/mesh',
    'model/vrml',
    'model/gltf+json',
    'model/obj',
    'message/http',
    'message/imdn+xml',
    'message/partial',
    'message/rfc822'
  ) NOT NULL,
  `status`      ENUM('Active', 'Block') NOT NULL DEFAULT 'Active',
  `createdOn`   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn`   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idxHost (`host`),
  INDEX idxPath (`path`),
  INDEX idxMime (`mime`),
  INDEX idxStatus (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4;